In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv("D:\Data Analytics\Projects\Anti-Money Laundering (AML) transaction monitoring\HI-Small_Trans.csv")
df.head(5)

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,01-09-2022 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,01-09-2022 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,01-09-2022 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,01-09-2022 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,01-09-2022 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

* Total Records

In [4]:
df.shape

(1048575, 11)

In [14]:
df.describe()

,From Bank,To Bank,Amount Received,Amount Paid,Is Laundering
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,5.883144e+04,7.081943e+04,7.138741e+06,5.918008e+06,5.865103e-04
std,9.098216e+04,9.089284e+04,6.034622e+08,4.695987e+08,2.421088e-02
min,1.000000e+00,1.000000e+00,1.000000e-06,1.000000e-06,0.000000e+00
25%,1.198000e+03,5.140000e+03,1.011950e+02,1.019200e+02,0.000000e+00
50%,1.501000e+04,2.216400e+04,1.925450e+03,1.928910e+03,0.000000e+00
75%,1.108360e+05,1.256070e+05,2.476846e+04,2.469339e+04,0.000000e+00
max,3.563000e+05,3.562940e+05,2.843830e+11,2.843830e+11,1.000000e+00

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 11 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Timestamp           1048575 non-null  object
 1   From Bank           1048575 non-null  int64
 2   Account             1048575 non-null  object
 3   To Bank             1048575 non-null  int64
 4   Account.1           1048575 non-null  object
 5   Amount Received     1048575 non-null  float64
 6   Receiving Currency  1048575 non-null  object
 7   Amount Paid         1048575 non-null  float64
 8   Payment Currency    1048575 non-null  object
 9   Payment Format      1048575 non-null  object
 10  Is Laundering       1048575 non-null  int64
dtypes: float64(2), int64(3), object(6)
memory usage: 88.0+ MB

In [17]:
df.isnull().sum()

Timestamp             0
From Bank             0
Account               0
To Bank               0
Account.1             0
Amount Received       0
Receiving Currency    0
Amount Paid           0
Payment Currency      0
Payment Format        0
Is Laundering         0
dtype: int64

In [18]:
df[df.duplicated]

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
863295,01-09-2022 16:20,12004,800C927C1,12004,800C927C0,0.000008,Bitcoin,0.080000,Euro,ACH,0
863296,01-09-2022 16:20,12004,800C927C1,220,813D8C1E1,0.000008,Bitcoin,0.000008,Bitcoin,Bitcoin,0

In [20]:
df.duplicated().sum()

np.int64(2)

In [21]:
print(df.columns.tolist())

['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1', 'Amount Received', 'Receiving Currency', 'Amount Paid', 'Payment Currency', 'Payment Format', 'Is Laundering']

In [22]:
df.shape

(1048575, 11)

In [24]:
df.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,01-09-2022 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,01-09-2022 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,01-09-2022 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,01-09-2022 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,01-09-2022 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [25]:
df.head(5).to_string()

'          Timestamp  From Bank    Account  To Bank  Account.1  Amount Received Receiving Currency  Amount Paid Payment Currency Payment Format  Is Laundering\n0  01-09-2022 00:20         10  8000EBD30       10  8000EBD30          3697.34          US Dollar      3697.34        US Dollar   Reinvestment              0\n1  01-09-2022 00:20       3208  8000F4580        1  8000F5340             0.01          US Dollar         0.01        US Dollar         Cheque              0\n2  01-09-2022 00:00       3209  8000F4670     3209  8000F4670         14675.57          US Dollar     14675.57        US Dollar   Reinvestment              0\n3  01-09-2022 00:02         12  8000F5030       12  8000F5030          2806.97          US Dollar      2806.97        US Dollar   Reinvestment              0\n4  01-09-2022 00:06         10  8000F5200       10  8000F5200         36682.97          US Dollar     36682.97        US Dollar   Reinvestment              0'

In [26]:
df["Is Laundering"].value_counts()

Is Laundering
0    1047960
1        615
Name: count, dtype: int64